# A program to input eight numberas from the user
# and display all the unique numbers 
s= set()
n= input("enter the number ")
s.add(int(n))
n= input("enter the number ")
s.add(int(n))
n= input("enter the number ")
s.add(int(n))
n= input("enter the number ")
s.add(int(n))
n= input("enter the number ")
s.add(int(n))
n= input("enter the number ")
s.add(int(n))
n= input("enter the number ")
s.add(int(n))
n= input("enter the number ")
s.add(int(n))
print(s)